In [2]:
import pandas as pd

In [3]:
inv = pd.read_csv("inventory1.csv", encoding = "windows-1252")
inv

,ProductName,Sales,Inventory,Price,December_2018,January,February,March,April,May,...,August,September,October,November,December_2019,QuantityPerYear,TransactionNo,RestockPoint,Rating,Bio
0,Set Of 2 Wooden Market Crates,526,785,21.47,2.2,1.909,1.882,1.917,1.579,1.857,...,2.133,3.625,2.286,2.682,8.667,2.517,16.308,3.0,5.000000,0
1,Christmas Star Wish List Chalkboard,3502,1151,10.65,0.0,1.000,0.000,0.000,0.000,0.000,...,9.455,16.200,13.286,10.055,16.469,12.872,34.250,13.0,2.990617,0
2,Storage Tin Vintage Leaf,739,1013,11.53,0.0,0.000,0.000,0.000,0.000,0.000,...,5.625,4.167,4.154,2.417,7.364,6.548,16.429,7.0,3.754392,0
3,Tree T-Light Holder Willie Winkie,364,1459,10.65,0.0,0.000,0.000,0.000,0.000,0.000,...,15.000,12.000,6.769,4.500,9.750,8.273,6.286,9.0,5.000000,0
4,Set Of 4 Knick Knack Tins Poppies,853,381,11.94,0.0,0.000,0.000,0.000,0.000,0.000,...,3.840,3.138,3.323,3.760,4.474,4.518,27.857,5.0,3.858950,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3748,Vintage Blue Tinsel Reel,2,966,10.68,2.0,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,NaN,1.000,NaN,4.975084,0
3749,Weekend Bag Vintage Rose Paisley,69,1766,18.09,69.0,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,NaN,1.000,NaN,5.000000,0
3750,Wrap Pink Flock,25,1517,10.68,25.0,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,NaN,1.000,NaN,2.887669,0
3751,Girly Pink Tool Set,5,1386,15.32,5.0,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,NaN,1.000,NaN,4.287054,0
3752,Pink Marshmallow Scarf Knitting Kit,36,1095,12.86,36.0,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,NaN,1.000,NaN,4.749061,1

In [5]:
def get_avg():
    avg = []
    
    for index, row in inv.iterrows():
        dec18 = row["December_2018"]
        jan = row["January"]
        feb = row["February"]
        mar = row["March"]
        apr = row["April"]
        may = row["May"]
        jun = row["June"]
        jul = row["July"]
        aug = row["August"]
        sep = row["September"]
        octo = row["October"]
        nov = row["November"]
        dec19 = row["December_2019"]
        
        total = dec18 + jan + feb + mar + apr + may + jun + jul + aug + sep + octo + nov + dec19
        total = total / 13
        avg.append(total)
        
    return avg

avg = get_avg()

In [6]:
inv["QuantityPerYear"] = avg
inv.to_csv('inven.csv', index=False)